export enum Role {
  CONSUMER = "CONSUMER",
  LMO = "LMO",
  GATC_ADMIN = "GATC_ADMIN",
  GATC_INSPECTOR = "GATC_INSPECTOR",
  ADMIN = "ADMIN",
}

export enum StakeholderType {
  MANUFACTURER = "MANUFACTURER",
  DEALER = "DEALER",
  REPAIRER = "REPAIRER",
  COMMERCIAL_USER = "COMMERCIAL_USER",
}

export enum InstrumentType {
  NON_AUTOMATIC_WEIGHING_INSTRUMENT = "NON_AUTOMATIC_WEIGHING_INSTRUMENT",
  AUTOMATIC_WEIGHING_INSTRUMENT = "AUTOMATIC_WEIGHING_INSTRUMENT",
  FUEL_DISPENSER = "FUEL_DISPENSER",
  STORAGE_TANK = "STORAGE_TANK",
  LENGTH_MEASURE = "LENGTH_MEASURE",
  CAPACITY_MEASURE = "CAPACITY_MEASURE",
  OTHER = "OTHER",
}

export enum ApplicationType {
  NEW = "NEW",
  RE_VERIFICATION = "RE_VERIFICATION",
}

export enum ApplicationStatus {
  SUBMITTED = "SUBMITTED",
  SCHEDULED = "SCHEDULED",
  INSPECTED = "INSPECTED",
  CERTIFIED = "CERTIFIED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum InspectionResult {
  PASSED = "PASSED",
  FAILED = "FAILED",
}

export enum NotificationChannel {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
  IN_APP = "IN_APP",
}

export enum NotificationType {
  APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED",
  INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED",
  CERTIFICATE_ISSUED = "CERTIFICATE_ISSUED",
  VERIFICATION_EXPIRING_SOON = "VERIFICATION_EXPIRING_SOON",
  VERIFICATION_EXPIRED = "VERIFICATION_EXPIRED",
  REJECTION_NOTICE = "REJECTION_NOTICE",
}

export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  STATUS_CHANGE = "STATUS_CHANGE",
  SIGN_CERTIFICATE = "SIGN_CERTIFICATE",
  ROTATE_KEY = "ROTATE_KEY",
}

